# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter: https://twitter.com/john29917958
google_plus: https://plus.google.com/+%E6%B1%AA%E5%AD%90%E8%B6%85
fb_admins: https://www.facebook.com/tzuchaowang
fb_app_id: